[project]
name = 'Blockchain-Based-Supply-Chain-Digital-Product-Passport'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.component-genealogy]
path = 'contracts/component-genealogy.clar'
clarity_version = 2
epoch = 2.5

[contracts.end-of-life]
path = 'contracts/end-of-life.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
